version: '3.8'
 
services:
  openjdk:
    image: openjdk:latest
    container_name: openjdk_container
 
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
 
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube_container
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres_container/mydb
      SONAR_JDBC_USERNAME: user
      SONAR_JDBC_PASSWORD: password
    ports:
      - "9000:9000" # Ensure this port is mapped
 
  nexus:
    image: sonatype/nexus3
    container_name: nexus_container
    ports:
      - "8081:8081"
